apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- inflated.yaml
#- ../agent/


# patchesStrategicMerge:
#   - patch-deployment.yaml
# - patch-cronjob.yaml
# - pod-modifier.yaml


patches:
 - target:
      kind: Deployment
      name: prism-agent-server
   path: patch-deployment.yaml
