name: "Upload to X-Ray"
description: "Uploads test results to X-Ray"
inputs:
  username:
    description: "XRAY_CLIENT_ID for authentication"
    required: true
  password:
    description: "XRAY_CLIENT_SECRET for authentication"
    required: true
  json:
    description: "Path to JSON to import"
    required: true
  execution_tag:
    description: "X-Ray Tests Execution to upload results"
    required: true
  scripts_path:
    description: "Path to Python scripts to update test execution in results"
    required: false
    default: "./tests/e2e-tests/src/test/resources/scripts"
  url:
    description: "X-Ray Cloud URL"
    required: false
    default: "https://xray.cloud.getxray.app"
runs:
  using: "composite"
  steps:
    - name: "Upload results to X-Ray"
      shell: bash
      run: |
        pip install -r ${{ inputs.scripts_path }}/requirements.txt
        ls -la ${PWD}/${{ inputs.json }}
        cat ${PWD}/${{ inputs.json }}
        ${{ inputs.scripts_path }}/add_test_execution.py "${PWD}/${{ inputs.json }}" "${{ inputs.execution_tag }}"
        XRAY_TOKEN=$(curl -H "Content-Type: application/json" \
            -X POST --data "{ \"client_id\": \"${{ inputs.username }}\", \
            \"client_secret\": \"${{ inputs.password }}\" }" \
            ${{ inputs.url }}/api/v1/authenticate | tr -d '"')
        curl -H "Content-Type: application/json" \
            -X POST -H "Authorization: Bearer ${XRAY_TOKEN}" \
            --data @"${{ inputs.json }}" \
            ${{ inputs.url }}/api/v1/import/execution/cucumber
