{{- if .Values.ingress.enabled }}
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: agent-route
  namespace: "{{ .Release.Namespace }}"
  labels:
    {{ template "labels.common" . }}
spec:
  http:
  - name: agent-rule
    match:
      hosts:
      {{- range .Values.ingress.applicationUrls }}
        - {{ . }}
      {{- end }}
      paths:
      - /prism-agent/*
    backends:
       - serviceName: agent-server-tapir-service
         servicePort: 8085
    authentication:
      enable: true
      type: keyAuth
    plugins:
    - name: proxy-rewrite
      enable: true
      config:
        regex_uri: ["^/prism-agent/(.*)","/$1"]
    - name: uri-blocker
      enable: true
      config:
        block_rules: ["_system/metrics"]
        rejected_message: "access to metrics resource is not allowed from an external location"
    {{ template "cors" . }}
    {{ template "consumer-restriction" . }}
    {{ template "headers.requestId" . }}
    {{ template "headers.security" . }}

---

apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: agent-didcomm-route
  namespace: "{{ .Release.Namespace }}"
  labels:
    {{ template "labels.common" . }}
spec:
  http:
  - name: agent-didcomm-rule
    match:
      hosts:
      {{- range .Values.ingress.applicationUrls }}
        - {{ . }}
      {{- end }}
      paths:
      - /prism-agent/didcomm*
    backends:
      - serviceName: agent-server-didcomm-service
        servicePort: 8090
    plugins:
    - name: proxy-rewrite
      enable: true
      config:
        regex_uri: ["^/prism-agent/didcomm(.*)", "/$1"]
    {{ template "cors" . }}
    {{ template "headers.requestId" . }}
    {{ template "headers.security" . }}

---

apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: agent-schema-registry-route
  namespace: "{{ .Release.Namespace }}"
  labels:
    {{ template "labels.common" . }}
spec:
  http:
  - name: agent-schema-registry-rule
    match:
      hosts:
      {{- range .Values.ingress.applicationUrls }}
        - {{ . }}
      {{- end }}
      paths:
      - /prism-agent/schema-registry/schemas/*
      methods:
      - GET
    backends:
      - serviceName: agent-server-tapir-service
        servicePort: 8085
    plugins:
    - name: proxy-rewrite
      enable: true
      config:
        regex_uri: ["^/prism-agent/schema-registry/schemas/(.*)", "/schema-registry/schemas/$1"]
    {{ template "cors" . }}
    {{ template "headers.requestId" . }}
    {{ template "headers.security" . }}

---

apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: agent-cred-def-registry-route
  namespace: "{{ .Release.Namespace }}"
  labels:
    {{ template "labels.common" . }}
spec:
  http:
  - name: agent-cred-def-registry-rule
    match:
      hosts:
      {{- range .Values.ingress.applicationUrls }}
      - {{ . }}
      {{- end }}
      paths:
        - /prism-agent/credential-definition-registry/definitions/*
      methods:
        - GET
    backends:
      - serviceName: agent-server-tapir-service
        servicePort: 8085
    plugins:
    - name: proxy-rewrite
      enable: true
      config:
        regex_uri: ["^/prism-agent/credential-definition-registry/definitions/(.*)", "/credential-definition-registry/definitions/$1"]
    {{ template "cors" . }}
    {{ template "headers.requestId" . }}
    {{ template "headers.security" . }}

---

apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: agent-docs-route
  namespace: "{{ .Release.Namespace }}"
  labels:
    {{ template "labels.common" . }}
spec:
  http:
  - name: agent-docs-rule
    match:
      hosts:
      {{- range .Values.ingress.applicationUrls }}
        - {{ . }}
      {{- end }}
      paths:
      - /prism-agent/docs/*
    backends:
      - serviceName: agent-server-tapir-service
        servicePort: 8085
    plugins:
    - name: proxy-rewrite
      enable: true
      config:
        regex_uri: ["^/prism-agent/docs/(.*)","/docs/$1"]
    {{ template "cors" . }}
    {{ template "headers.requestId" . }}
    {{ template "headers.security" . }}

---
{{- end }}
