apiVersion: "secretgenerator.mittwald.de/v1alpha1"
kind: StringSecret
metadata:
  name: "agent-wallet-seed"
  namespace: {{ .Release.Namespace }}
spec:
  forceRegenerate: false
  fields:
    - fieldName: "seed"
      encoding: "hex"
      length: "128"
