apiVersion: "secretgenerator.mittwald.de/v1alpha1"
kind: StringSecret
metadata:
  name: "agent-api-key-salt"
  namespace: {{ .Release.Namespace }}
spec:
  forceRegenerate: false
  fields:
    - fieldName: "salt"
      encoding: "base64"
      length: "16"
