apiVersion: "secretgenerator.mittwald.de/v1alpha1"
kind: StringSecret
metadata:
  name: "agent-admin-token"
  namespace: {{ .Release.Namespace }}
spec:
  forceRegenerate: false
  fields:
    - fieldName: "token"
      encoding: "base64"
      length: "32"
